#!/usr/bin/env bash
# Install Nginx web server on the web server machine
# Nginx should be listening on port 80 and redirect /redirect_me to another page

# Update the package repositories
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx HTTP traffic in the firewall
sudo ufw allow 'Nginx HTTP'

# Create the index.html file with "Hello World!" content
echo "Hello World!" > sudo /var/www/html/index.nginx-debian.html

# Add a line to the Nginx configuration file for redirection
sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

# Start the Nginx service
sudo service nginx start
