#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me


# Allow incoming HTTP traffic through UFW firewall
sudo ufw allow 'Nginx HTTP'

# Create an index file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index

# Create a backup of the default configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Add a redirection rule to the default Nginx configuration
# The rule redirects /redirect_me path to https://www.youtube.com/watch?v=QH2-TGUlwu4
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
