#!/usr/bin/env bash
# Script to configure custom 404 page in Nginx

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Create a backup of the default configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/jossvega103 permanent;" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > /usr/share/nginx/html/page_error_404.html

sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
