#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo sed -i 's/^\(ENABLED=\).*/\11/' /etc/default/haproxy

# Create a new HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend load_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server web-01 34.204.95.241:80 check
    server web-02 52.87.230.196:80 check
EOT

# Restart HAProxy service
sudo service haproxy restart
