#!/usr/bin/env bash
# This script opens port 80 for Nginx

# Update Nginx configuration to listen on port 80
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

# Restart Nginx to apply the configuration changes
service nginx restart
