#!/usr/bin/env bash
# Configure Nginx server to listen on port 80

# Update the Nginx configuration file to remove "default_server" option from the listen directive
sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default

# Restart the Nginx service to apply the configuration changes
service nginx restart

# Terminate the oldest Nginx process to ensure a clean restart
pkill -o nginx
