#!/usr/bin/env bash
# Run the whoami command under the user passed as an argument

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# Set the HOME environment variable for the specified user
export HOME=$(getent passwd "$1" | cut -d: -f6)

# Run whoami command as the specified user
sudo -H -u "$1" whoami
