#!/usr/bin/env bash
# Run the whoami command under the user passed as an argument

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# Get the user's home directory
user_home=$(getent passwd "$1" | awk -F':' '{print $6}')

# Run whoami command as the specified user
sudo -H -u "$1" whoami
