#!/usr/bin/env bash                                                             
# This script that accepts one argument whoami                                       
# It runs the 'whoami' command under the user passed as argument
su "$1" -s /bin/bash -c 'whoami'
