#!/usr/bin/env bash

# Stop Apache2 (Assuming Apache2 is running and needs to be stopped)
pkill "apache2"

# Modify the Nginx configuration file to use 'nginx' user instead of 'root'
sudo sed -i '1i user nginx;' /etc/nginx/nginx.conf

# Add '80' to the 'listen' directive in the default Nginx configuration file
# This will ensure Nginx listens on port 80
sudo sed -i 's/\<80\>/&80/' /etc/nginx/sites-available/default

# Set the permissions of the Nginx configuration file to 644 (owner read/write, group read, others read)
# This ensures the file is not writable by others and only the owner can write to it.
sudo chmod 644 /etc/nginx/nginx.conf

# Restart Nginx service running as 'nginx' user
sudo -u nginx service nginx restart
