#!/usr/bin/env bash

# This Bash script gracefully restarts Gunicorn

# Get the PIDs of the existing Gunicorn processes
gunicorn_pids=$(pgrep -f "[g]unicorn")

# Print the current Gunicorn processes
echo "Current Gunicorn processes:"
ps auxf | grep "[g]unicorn"

# Gracefully reload Gunicorn
echo "Reloading Gunicorn..."
kill -HUP $gunicorn_pids

# Wait for a moment to allow the workers to gracefully shut down
sleep 5

# Print the updated Gunicorn processes
echo "Updated Gunicorn processes:"
ps auxf | grep "[g]unicorn"

echo "Gunicorn reload completed."
